version: '3'
services:

    nginx:
        build: requirements/nginx/
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "~/data/nginx:/var/log/nginx/"
        depends_on:
            - wordpress
        networks:
            - frontend
        restart: always
    
    wordpress:
        build: requirements/wordpress/
        container_name: wordpress
        ports:
            - "9000:9000"
        volumes:
            - "~/data:/var/www/html"
        networks:
            - frontend
            - backend
        depends_on:
            - mariadb
        restart: always
        environment:
            DB_HOSTNAME: ${DB_HOSTNAME}
            WP_DATABASE_USR: ${WP_DATABASE_USR}
            WP_DATABASE_PWD: ${WP_DATABASE_PWD}
            WP_DATABASE_EMAIL: ${WP_DATABASE_EMAIL}
            WP_DATABASE_NAME: ${WP_DATABASE_NAME}
            DOMAIN_NAME: ${DOMAIN_NAME}

        
    mariadb:
        build: requirements/mariadb/
        container_name: mariadb
        ports:
            - "3306:3306"
        volumes:
            - "~/data/mariadb:/var/lib/mysql"
        networks:
            - backend
        restart: always
        environment:
            DB_ROOT_PWD: ${DB_ROOT_PWD}
            WP_DATABASE_NAME: ${WP_DATABASE_NAME}
            WP_DATABASE_USR: ${WP_DATABASE_USR}
            WP_DATABASE_PWD: ${WP_DATABASE_PWD}


networks:
    frontend:
    backend:
