version: '3'
services:

    nginx:
        image: nginx
        build: requirements/nginx/
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - nginx:/var/log/nginx
        depends_on:
            - wordpress
        networks:
            - frontend
        restart: always
    
    wordpress:
        image: wordpress
        build: requirements/wordpress/
        container_name: wordpress
        ports:
            - "9000:9000"
        volumes:
            - wp_files:/var/www/html/wordpress
        networks:
            - frontend
            - backend
        depends_on:
            - mariadb
        restart: always
        environment:
            DB_HOSTNAME: ${DB_HOSTNAME}
            DOMAIN_NAME: ${DOMAIN_NAME}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_ADMIN: ${DATABASE_ADMIN}
            DATABASE_ADMIN_PWD: ${DATABASE_ADMIN_PWD}
            WP_ADMIN_USR: ${WP_ADMIN_USR}
            WP_ADMIN_PWD: ${WP_ADMIN_PWD}
            WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
            WP_USR: ${WP_USR}
            WP_PWD: ${WP_PWD}
            WP_EMAIL: ${WP_EMAIL}

        
    mariadb:
        image: mariadb
        build: requirements/mariadb/
        container_name: mariadb
        ports:
            - "3306:3306"
        volumes:
            - wp_database:/var/lib/mysql/
        networks:
            - backend
        restart: always
        environment:
            DB_ROOT_PWD: ${DB_ROOT_PWD}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_ADMIN: ${DATABASE_ADMIN}
            DATABASE_ADMIN_PWD: ${DATABASE_ADMIN_PWD}


networks:
    frontend:
    backend:

volumes:
    wp_files:
        driver: local
        name: wp_files
        driver_opts:
            type: none
            o: bind
            device: /home/ddelladi/data/wp_files
    wp_database:
        driver: local
        name: wp_database
        driver_opts:
            type: none
            o: bind
            device: /home/ddelladi/data/wp_database
    nginx:
        driver: local
        name: nginx
        driver_opts:
            type: none
            o: bind
            device: /home/ddelladi/data/nginx