version: '3'
services:

    nginx:
        build: requirements/nginx/
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "~/data/nginx:/var/log/nginx/"
        depends_on:
            - wordpress
        networks:
            - frontend
        restart: always
    
    wordpress:
        build: requirements/wordpress/
        container_name: wordpress
        ports:
            - "9000:9000"
        volumes:
            - "~/data:/var/www/html/wordpress"
        networks:
            - frontend
            - backend
        depends_on:
            - mariadb
        restart: always
        environment:
            DB_HOSTNAME: ${DB_HOSTNAME}
            DOMAIN_NAME: ${DOMAIN_NAME}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_ADMIN: ${DATABASE_ADMIN}
            DATABASE_ADMIN_PWD: ${DATABASE_ADMIN_PWD}
            WP_ADMIN_USR: ${WP_ADMIN_USR}
            WP_ADMIN_PWD: ${WP_ADMIN_PWD}
            WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
            WP_USR: ${WP_USR}
            WP_PWD: ${WP_PWD}
            WP_EMAIL: ${WP_EMAIL}

        
    mariadb:
        build: requirements/mariadb/
        container_name: mariadb
        ports:
            - "3306:3306"
        volumes:
            - "~/data/mariadb:/var/lib/mysql/mysql/${DATABASE_NAME}"
        networks:
            - backend
        restart: always
        environment:
            DB_ROOT_PWD: ${DB_ROOT_PWD}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_ADMIN: ${DATABASE_ADMIN}
            DATABASE_ADMIN_PWD: ${DATABASE_ADMIN_PWD}


networks:
    frontend:
    backend:
